server:
  port: 80

mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://kingmysql.mysql.rds.aliyuncs.com:3306/kekeonline?serverTimezone=UTC&CharacterEncoding=UTF-8&allowMultiQueries=true
    username: kekeonline
    password: Zxcv6666
    driver-class-name: com.mysql.cj.jdbc.Driver
  static-locations: classpath:/static/

  mail:
    host: smtp.qq.com
    username: 1327883751@qq.com
    password: jjqutrcbromvhhhg
    default-encoding: UTF-8
    port: 465
    auth: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true
      imap:
        ssl:
          socketFactory:
            fallback: false

mail:
  fromMail:
    addr: 1327883751@qq.com


#alipay:
#  appid: 2021000116670110
#  gatewayUrl: https://openapi.alipaydev.com/gateway.do
#  format: json
#  charset: utf-8
#  signType: RSA2
#  returnUrl: http://172.20.91.255:80/alipay/return（同步回调，不需要配置，只要路径正确，本地可以访问即可）
#  notifyUrl: http://172.20.91.255:80/alipay/notify（异步回调，需要在支付宝上配置路径，外网可访问）
#  app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCtTU9/CxNDyn9D/iTtFiVrRIphqIkBtDTzU54yVmXM5gWrqeHcicHQQq6LOgQJSPg4hXhLfCee1jZ0cxBjbApPTooyEtxAdwK+/hOPN7vOGKazJ6OT8EH0naQudTm+pxGF8IOj/XE/HfzBwo7ypYhYB+3vLcIQxiPNXccrYknjDDcw3OZVFzUhKpiw7MtNLB7nbnGnzwMFGa2Cjm+blyLeAcgDXEbH+eNj2x+qCvVkrg0Wm/g6OVewWGRVM/XDVll6jZtIhaWgQ2YMjUimUNLSZjhO5v2hCzYVFzoSKl7+vLFicpm1T4tVLjHAqj0nq37iGJeDW05OnOI222OOYZZZAgMBAAECggEBAJLpV/vl4qX0UuDL4HfP71a42uqg2cxE/SJNf21CyrfhQ2tb72lqqo+nB5plSyin4CziELFFBb1j8PPU2069Nxw2A3chf+9yNDS+5MvjPmUfhqmXb9cotHDu9lCf9ZzGulcmJiJt5oPQIwYKre3LIAMoba71xm872PvuhLolb2d1/QS9yroQk+CgpieKypo/PzAJBCxn+2Zj/SIuTQ1p5FPJoslvZSlLBrdUVZElHzM25ynuwj97SgRb4ihuX2y2fdR4Hoj0/EidqkTlzqWiNeuiEg5YYGg8onjb+0/24XFFVnyJt9yGpmyXaqvm3SY//0wSy4IVtn0rtJjPCpu+MoECgYEA3SkLSG/8fShFDZerV5CSRdWMEtBDyBunLm6mFLQMxKwchU3jyZ21DZUKcREKiRLxfCoSRlsk64Q0q7c+tgLyj/muf/g3E+bC+tCORJ1jLLRcutqRWj5Sa4ZYGwXYoPbxtPGoQEJOI2fk5gyAKELFM+/35e8agRF/FxVbf5guLEkCgYEAyJo8LlpG2TxP50h0VhSJ178AWl2jFzL5MQiHXgsyUANpUwshXEHPR2ZScL5u0l0lLVR7mAeAkmHxDO9nifhimIWV6kRevxPEANE/6R9xbVb6CDR7K6kuRT6nqDvzOA9rgw5HEa4tcsSkFDbWN8xd1kraHd/C7iKKtgUQ5gbseZECgYAKX5x531bWgAcNJioRR2S1Bdk2ILKtNi7XTLVZj0ByESidUBP5Jv6RDoaY2xXFbDALhOWqiyfmLCNUUpoMa4L5Idr/gaMDufU3UoT5zvAR7rvSv+HFe9rd1EVZryKEGlEoDZW4veNwYbUo3Tk9qjQZxY25KUfy+eEeMhBCod64kQKBgHf0Kqp5F0aNlyYxIEfdDjQxpa9jsMONmo8kj3W/8j0AXTnoPPGi9KS4XfHHHhOy2SlLDIDzc4GVCYR3oA1TtvmHYAbvDUzrL9hhR/tJ7xS33tmLMGACUYXcmnqyJpVOOzbqEbtT0R+A0LC5vc0t6qrapaUZicHGa/W9/8XdPAjRAoGAQuANiHG28Z6MpLnLIZXaPUWW2qb8nAEJeA1TGKDxs1ZUYHGPEEwAyKMGlypWSsQR53OA2vJDO7P2rtQo2SHVG40haUPXuhiYB8FxUBM0s2ECTLtppyGOX6IfeHZrrIiCvnMScRrw0MvuXArzBjRBj649XRLONsDsPr98WWPDFKo=
#  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAls9J375dQzn9jD4qSHYsvyHjOwBugzCMa/clJdkI1/2QDDvKxdHgWJDCUWkNDUsq+G0AbSoK5mU8IwudNVRBmHp0ncw19Rhq/spZWuEjmalfeZVN8a4qbpy0YdjRfltI3JzO98tvW5ZvlfI2chHQyOwIVE+4NvaQb51AO01F6dbZ1Gi5Cye3S6Go3nNWRuV7+NameDL922aeqP/nrWmiMCzMExzaNDysxLIT9goqLiYuVZ/fozzz2sfVRXbDX9dT1hCGWlNIhOw2uKuefwxzKNr8tT3IxPCiOzqvdQCqdnPR6uaKOQakIrk0R0gtVIqlGyrA4eW+fJx3AY4ceyI0gQIDAQAB
#
alipay:
  appid: 2016101800716266
  app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCAJ3GHhf97sJY0EZhYdw+bvmv91IHXIE2dSZx2WNa5gonJT1klut0W9R5HB0OS1q3A+yiV2epeUDwFMFVdOBnR8RKoLzqH0FHrgrJv3NRGel77DWpJiuEvk3I0mlb0CTd6mXxAwrdz/6ytldxXj6NUG1t+own5I5stK5I34RFQe1N2kP5VrWvC5u19W3kr/mBml0eAV4wKqtaB+i4nE2/zKar5cUe9r+24fSeZu5tU/Rqj4IscfUJW0cbqfmuSD3Sez5HiafbEli7mTufgH0FGwezd5lwUpoADvfDEEXBgblMjfJRROln1DW7ab8fo6QhQHFZE/hepLLW2RmKNc841AgMBAAECggEAVxT2Y0XdnjoXRthx8iMtWwJhNYFSnVEZDHk5tX2Wo0YdxMqDZEz+8Rus8EzyUPRJ62l/YZxLUr0om8oFJ6v4d51dtSUqm6EmGWedQsAHCsEai3PJNqIFdKO3piD+VyNwLIHhWcw2hr9EokvEB0fWj09rs7isDTxxtJb367qnXk0DWB7HOaRxU8sjbGxJj0owpbh+PlarGvZN4A7RoNaE0kJPC8yEQ8TDRKtJaIEN0xoxO/ZvGZv5kiMCc2U2skhpJWkKsRSNMf9CUlmBKlTjJAJ62AV1GClC6yuW9+LMU/Bd6SeaiSitQ8sPmjHMIf6fLY7CDLbgDSSe0RdJxpdVYQKBgQDgNMRwB+oaMj6V8sbviZVhcXe9uJcqB9c1JKQ45AhFwJ77c2XLqvTl4WH9MWjk6bwOtDOVo76nZmtl8GASF5xbp1B3MQ/3j5c3sL88E0IevuvpqWbzALRqRooC2BqZ31z9hEZM8/ShVqTT0PxDMYKUpgoNiI5qm0QwQ2+YZrKa7QKBgQCSU8BE7Ul6dXhUL8uLqoRb/4zdQAjaK1WWsXY1jjvW+KRCWLtJTOTriaWi3R6QzLEc0xcKzGuCS14Ix88oMuzybfeazd5iY6d/7GOTqESsy5Q7lXxFZh0CRCoO7tKUohJmGCE2TdSdt/h0d+ysQwim3B/XaYrp+LiVmomyWOvvaQKBgHOHfTllOqIpBcrqgMvpj0nY2CSwu2PzClfd+6k9B2455TIYsnmSLANQcdev4Ccksby56mLPL2y+/9RVWou4Et+/hV0FsP6VxQvzTXc9TTLeml2a5uuMj2q70l3I0Vw8loQj5r28b2+7X8+tvm85Udoa/M8gcJJKU4azGQvkz1+5AoGAGtuOddhL3VNEY8dmB9ujcbNlKpL/TPQZQJCQDuJtb1ax54+byKd5eRYJtev6GT/I3m6MUyoULZUhzGDIUCuQvCqdAOf6gnqiGuPLnyWKfWDcc1dLuP02I91ZDuac9jUNRXn2Vp5QgSZsTwxX/4JKSz4qBgLUQX+qeaMk1PxnSckCgYEA1IX/KxWCcmrAwIzH0HnL3ioKMcYSL0MIe6nDHGbdpo2pigd0lkA2da/6RYpggE+9yzoVcfqfrTfwFTSeoKptEKfHRikB3z/IGz0jaCuQoIvuoD/jv8ryuwiwBOCHltkRiye/CbIjfJ8xyfwt/YUjJ7CPIIc+XKoWcI46PC5VT5k=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt3rHXYvIU9k1pvIQLrZ0x9MXlZCjA/ZXw3zr7TVPhaBvck61OMLojnyfJaC8tXcqvPaM7J+AcA4W4eky86lMsAr35Tg7wCpNiXSY8ThJZSHdz5gOOLCEyH9zbN2dkwumz8khimtVeJb1+A8clK6jEcY2MKiNlJkVHS33CS1BchV3lVrg14Qp7ulgBj53D93xmhJ1GXkrjjyvP8DiaHZNN1OvVk7/o/kTy7q1qWDULN6Bzq6L68NN6+zaPVFl0A2qVK2dKsSl9aRJIRoIfykHnV4YK7Zb3osA3Fwa8kXg4sNXv3jVxD78qUJeRh5UcK32ERhz7WSpCijgaqtEXw73CQIDAQAB
  notify_url:  http://pegwv3.natappfree.cc/payment/notify_url
  return_url: http://localhost:8080/payment/return_url
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do




